export const nationalitiesWithFlags = [
  { name: 'Afghan', code: 'AF', flag: '🇦🇫' },
  { name: 'Albanian', code: 'AL', flag: '🇦🇱' },
  { name: 'Algerian', code: 'DZ', flag: '🇩🇿' },
  { name: 'Andorran', code: 'AD', flag: '🇦🇩' },
  { name: 'Angolan', code: 'AO', flag: '🇦🇴' },
  { name: 'Argentine', code: 'AR', flag: '🇦🇷' },
  { name: 'Armenian', code: 'AM', flag: '🇦🇲' },
  { name: 'Australian', code: 'AU', flag: '🇦🇺' },
  { name: 'Austrian', code: 'AT', flag: '🇦🇹' },
  { name: 'Azerbaijani', code: 'AZ', flag: '🇦🇿' },
  { name: 'Bahraini', code: 'BH', flag: '🇧🇭' },
  { name: 'Bangladeshi', code: 'BD', flag: '🇧🇩' },
  { name: 'Barbadian', code: 'BB', flag: '🇧🇧' },
  { name: 'Belarusian', code: 'BY', flag: '🇧🇾' },
  { name: 'Belgian', code: 'BE', flag: '🇧🇪' },
  { name: 'Belizean', code: 'BZ', flag: '🇧🇿' },
  { name: 'Beninese', code: 'BJ', flag: '🇧🇯' },
  { name: 'Bhutanese', code: 'BT', flag: '🇧🇹' },
  { name: 'Bolivian', code: 'BO', flag: '🇧🇴' },
  { name: 'Bosnian', code: 'BA', flag: '🇧🇦' },
  { name: 'Botswanan', code: 'BW', flag: '🇧🇼' },
  { name: 'Brazilian', code: 'BR', flag: '🇧🇷' },
  { name: 'British', code: 'GB', flag: '🇬🇧' },
  { name: 'Bruneian', code: 'BN', flag: '🇧🇳' },
  { name: 'Bulgarian', code: 'BG', flag: '🇧🇬' },
  { name: 'Burkinabe', code: 'BF', flag: '🇧🇫' },
  { name: 'Burmese', code: 'MM', flag: '🇲🇲' },
  { name: 'Burundian', code: 'BI', flag: '🇧🇮' },
  { name: 'Cambodian', code: 'KH', flag: '🇰🇭' },
  { name: 'Cameroonian', code: 'CM', flag: '🇨🇲' },
  { name: 'Canadian', code: 'CA', flag: '🇨🇦' },
  { name: 'Cape Verdean', code: 'CV', flag: '🇨🇻' },
  { name: 'Central African', code: 'CF', flag: '🇨🇫' },
  { name: 'Chadian', code: 'TD', flag: '🇹🇩' },
  { name: 'Chilean', code: 'CL', flag: '🇨🇱' },
  { name: 'Chinese', code: 'CN', flag: '🇨🇳' },
  { name: 'Colombian', code: 'CO', flag: '🇨🇴' },
  { name: 'Comoran', code: 'KM', flag: '🇰🇲' },
  { name: 'Congolese', code: 'CG', flag: '🇨🇬' },
  { name: 'Costa Rican', code: 'CR', flag: '🇨🇷' },
  { name: 'Croatian', code: 'HR', flag: '🇭🇷' },
  { name: 'Cuban', code: 'CU', flag: '🇨🇺' },
  { name: 'Cypriot', code: 'CY', flag: '🇨🇾' },
  { name: 'Czech', code: 'CZ', flag: '🇨🇿' },
  { name: 'Danish', code: 'DK', flag: '🇩🇰' },
  { name: 'Djiboutian', code: 'DJ', flag: '🇩🇯' },
  { name: 'Dominican', code: 'DO', flag: '🇩🇴' },
  { name: 'Dutch', code: 'NL', flag: '🇳🇱' },
  { name: 'Ecuadorian', code: 'EC', flag: '🇪🇨' },
  { name: 'Egyptian', code: 'EG', flag: '🇪🇬' },
  { name: 'Salvadoran', code: 'SV', flag: '🇸🇻' },
  { name: 'Equatorial Guinean', code: 'GQ', flag: '🇬🇶' },
  { name: 'Eritrean', code: 'ER', flag: '🇪🇷' },
  { name: 'Estonian', code: 'EE', flag: '🇪🇪' },
  { name: 'Ethiopian', code: 'ET', flag: '🇪🇹' },
  { name: 'Fijian', code: 'FJ', flag: '🇫🇯' },
  { name: 'Finnish', code: 'FI', flag: '🇫🇮' },
  { name: 'French', code: 'FR', flag: '🇫🇷' },
  { name: 'Gabonese', code: 'GA', flag: '🇬🇦' },
  { name: 'Gambian', code: 'GM', flag: '🇬🇲' },
  { name: 'Georgian', code: 'GE', flag: '🇬🇪' },
  { name: 'German', code: 'DE', flag: '🇩🇪' },
  { name: 'Ghanaian', code: 'GH', flag: '🇬🇭' },
  { name: 'Greek', code: 'GR', flag: '🇬🇷' },
  { name: 'Grenadian', code: 'GD', flag: '🇬🇩' },
  { name: 'Guatemalan', code: 'GT', flag: '🇬🇹' },
  { name: 'Guinean', code: 'GN', flag: '🇬🇳' },
  { name: 'Guinea-Bissauan', code: 'GW', flag: '🇬🇼' },
  { name: 'Guyanese', code: 'GY', flag: '🇬🇾' },
  { name: 'Haitian', code: 'HT', flag: '🇭🇹' },
  { name: 'Honduran', code: 'HN', flag: '🇭🇳' },
  { name: 'Hungarian', code: 'HU', flag: '🇭🇺' },
  { name: 'Icelandic', code: 'IS', flag: '🇮🇸' },
  { name: 'Indian', code: 'IN', flag: '🇮🇳' },
  { name: 'Indonesian', code: 'ID', flag: '🇮🇩' },
  { name: 'Iranian', code: 'IR', flag: '🇮🇷' },
  { name: 'Iraqi', code: 'IQ', flag: '🇮🇶' },
  { name: 'Irish', code: 'IE', flag: '🇮🇪' },
  { name: 'Israeli', code: 'IL', flag: '🇮🇱' },
  { name: 'Italian', code: 'IT', flag: '🇮🇹' },
  { name: 'Ivorian', code: 'CI', flag: '🇨🇮' },
  { name: 'Jamaican', code: 'JM', flag: '🇯🇲' },
  { name: 'Japanese', code: 'JP', flag: '🇯🇵' },
  { name: 'Jordanian', code: 'JO', flag: '🇯🇴' },
  { name: 'Kazakhstani', code: 'KZ', flag: '🇰🇿' },
  { name: 'Kenyan', code: 'KE', flag: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮' },
  { name: 'North Korean', code: 'KP', flag: '🇰🇵' },
  { name: 'South Korean', code: 'KR', flag: '🇰🇷' },
  { name: 'Kuwaiti', code: 'KW', flag: '🇰🇼' },
  { name: 'Kyrgyz', code: 'KG', flag: '🇰🇬' },
  { name: 'Laotian', code: 'LA', flag: '🇱🇦' },
  { name: 'Latvian', code: 'LV', flag: '🇱🇻' },
  { name: 'Lebanese', code: 'LB', flag: '🇱🇧' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸' },
  { name: 'Liberian', code: 'LR', flag: '🇱🇷' },
  { name: 'Libyan', code: 'LY', flag: '🇱🇾' },
  { name: 'Liechtensteiner', code: 'LI', flag: '🇱🇮' },
  { name: 'Lithuanian', code: 'LT', flag: '🇱🇹' },
  { name: 'Luxembourgish', code: 'LU', flag: '🇱🇺' },
  { name: 'Macedonian', code: 'MK', flag: '🇲🇰' },
  { name: 'Malagasy', code: 'MG', flag: '🇲🇬' },
  { name: 'Malawian', code: 'MW', flag: '🇲🇼' },
  { name: 'Malaysian', code: 'MY', flag: '🇲🇾' },
  { name: 'Maldivian', code: 'MV', flag: '🇲🇻' },
  { name: 'Malian', code: 'ML', flag: '🇲🇱' },
  { name: 'Maltese', code: 'MT', flag: '🇲🇹' },
  { name: 'Marshallese', code: 'MH', flag: '🇲🇭' },
  { name: 'Mauritanian', code: 'MR', flag: '🇲🇷' },
  { name: 'Mauritian', code: 'MU', flag: '🇲🇺' },
  { name: 'Mexican', code: 'MX', flag: '🇲🇽' },
  { name: 'Micronesian', code: 'FM', flag: '🇫🇲' },
  { name: 'Moldovan', code: 'MD', flag: '🇲🇩' },
  { name: 'Monacan', code: 'MC', flag: '🇲🇨' },
  { name: 'Mongolian', code: 'MN', flag: '🇲🇳' },
  { name: 'Montenegrin', code: 'ME', flag: '🇲🇪' },
  { name: 'Moroccan', code: 'MA', flag: '🇲🇦' },
  { name: 'Mozambican', code: 'MZ', flag: '🇲🇿' },
  { name: 'Namibian', code: 'NA', flag: '🇳🇦' },
  { name: 'Nauruan', code: 'NR', flag: '🇳🇷' },
  { name: 'Nepalese', code: 'NP', flag: '🇳🇵' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
  { name: 'Nicaraguan', code: 'NI', flag: '🇳🇮' },
  { name: 'Nigerian', code: 'NG', flag: '🇳🇬' },
  { name: 'Nigerien', code: 'NE', flag: '🇳🇪' },
  { name: 'Norwegian', code: 'NO', flag: '🇳🇴' },
  { name: 'Omani', code: 'OM', flag: '🇴🇲' },
  { name: 'Pakistani', code: 'PK', flag: '🇵🇰' },
  { name: 'Palauan', code: 'PW', flag: '🇵🇼' },
  { name: 'Palestinian', code: 'PS', flag: '🇵🇸' },
  { name: 'Panamanian', code: 'PA', flag: '🇵🇦' },
  { name: 'Papua New Guinean', code: 'PG', flag: '🇵🇬' },
  { name: 'Paraguayan', code: 'PY', flag: '🇵🇾' },
  { name: 'Peruvian', code: 'PE', flag: '🇵🇪' },
  { name: 'Philippine', code: 'PH', flag: '🇵🇭' },
  { name: 'Polish', code: 'PL', flag: '🇵🇱' },
  { name: 'Portuguese', code: 'PT', flag: '🇵🇹' },
  { name: 'Qatari', code: 'QA', flag: '🇶🇦' },
  { name: 'Romanian', code: 'RO', flag: '🇷🇴' },
  { name: 'Russian', code: 'RU', flag: '🇷🇺' },
  { name: 'Rwandan', code: 'RW', flag: '🇷🇼' },
  { name: 'Saint Lucian', code: 'LC', flag: '🇱🇨' },
  { name: 'Samoan', code: 'WS', flag: '🇼🇸' },
  { name: 'San Marinese', code: 'SM', flag: '🇸🇲' },
  { name: 'Sao Tomean', code: 'ST', flag: '🇸🇹' },
  { name: 'Saudi Arabian', code: 'SA', flag: '🇸🇦' },
  { name: 'Senegalese', code: 'SN', flag: '🇸🇳' },
  { name: 'Serbian', code: 'RS', flag: '🇷🇸' },
  { name: 'Seychellois', code: 'SC', flag: '🇸🇨' },
  { name: 'Sierra Leonean', code: 'SL', flag: '🇸🇱' },
  { name: 'Singaporean', code: 'SG', flag: '🇸🇬' },
  { name: 'Slovak', code: 'SK', flag: '🇸🇰' },
  { name: 'Slovenian', code: 'SI', flag: '🇸🇮' },
  { name: 'Solomon Islander', code: 'SB', flag: '🇸🇧' },
  { name: 'Somali', code: 'SO', flag: '🇸🇴' },
  { name: 'South African', code: 'ZA', flag: '🇿🇦' },
  { name: 'Spanish', code: 'ES', flag: '🇪🇸' },
  { name: 'Sri Lankan', code: 'LK', flag: '🇱🇰' },
  { name: 'Sudanese', code: 'SD', flag: '🇸🇩' },
  { name: 'Surinamese', code: 'SR', flag: '🇸🇷' },
  { name: 'Swazi', code: 'SZ', flag: '🇸🇿' },
  { name: 'Swedish', code: 'SE', flag: '🇸🇪' },
  { name: 'Swiss', code: 'CH', flag: '🇨🇭' },
  { name: 'Syrian', code: 'SY', flag: '🇸🇾' },
  { name: 'Taiwanese', code: 'TW', flag: '🇹🇼' },
  { name: 'Tajik', code: 'TJ', flag: '🇹🇯' },
  { name: 'Tanzanian', code: 'TZ', flag: '🇹🇿' },
  { name: 'Thai', code: 'TH', flag: '🇹🇭' },
  { name: 'Togolese', code: 'TG', flag: '🇹🇬' },
  { name: 'Tongan', code: 'TO', flag: '🇹🇴' },
  { name: 'Trinidad & Tobago', code: 'TT', flag: '🇹🇹' },
  { name: 'Tunisian', code: 'TN', flag: '🇹🇳' },
  { name: 'Turkish', code: 'TR', flag: '🇹🇷' },
  { name: 'Turkmen', code: 'TM', flag: '🇹🇲' },
  { name: 'Tuvaluan', code: 'TV', flag: '🇹🇻' },
  { name: 'Ugandan', code: 'UG', flag: '🇺🇬' },
  { name: 'Ukrainian', code: 'UA', flag: '🇺🇦' },
  { name: 'Uruguayan', code: 'UY', flag: '🇺🇾' },
  { name: 'American', code: 'US', flag: '🇺🇸' },
  { name: 'Uzbekistani', code: 'UZ', flag: '🇺🇿' },
  { name: 'Vanuatuan', code: 'VU', flag: '🇻🇺' },
  { name: 'Venezuelan', code: 'VE', flag: '🇻🇪' },
  { name: 'Vietnamese', code: 'VN', flag: '🇻🇳' },
  { name: 'Yemeni', code: 'YE', flag: '🇾🇪' },
  { name: 'Zambian', code: 'ZM', flag: '🇿🇲' },
  { name: 'Zimbabwean', code: 'ZW', flag: '🇿🇼' },
]